#!/bin/bash

#PBS -l nodes=1:ppn=4,walltime=1:30:00
#PBS -N applywarppeaksbundles

echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.3.2 ./mri_vol2vol_peaks_bundles.sh
time singularity exec -e docker://brainlife/fsl:6.0.4-patched2 ./applywarp_peaks_bundles.sh